// Generated by scripts/measure-audio.ts — do not edit by hand.
// Narration audio durations in seconds, measured post-TTS.
// The video composition derives each scene's length from these values.
// TTS voice: he-IL-HilaNeural
import type { NarrationSet } from "./texts";

export const audioDurations: Record<keyof NarrationSet, number> = {
  opening: 17.06,
  variantIntroChrom: 12.41,
  variantIntroHelix: 10.75,
  variantIntroBase: 7.46,
  categories: 23.95,
  notVUS: 16.82,
  specificVariant: 34.51,
  whyUncertain: 20.3,
  timeline: 20.3,
  closing: 11.74,
};
