// Generated by scripts/measure-audio.ts — do not edit by hand.
// Narration audio durations in seconds, measured post-TTS.
// The video composition derives each scene's length from these values.
// TTS voice: he-IL-HilaNeural
import type { NarrationSet } from "./texts";

export const audioDurations: Record<keyof NarrationSet, number> = {
  opening: 17.06,
  variantIntro: 20.95,
  categories: 23.95,
  notVUS: 16.82,
  specificVariant: 45.38,
  whyUncertain: 20.3,
  timeline: 20.45,
  closing: 11.74,
};
