/**
 * Measures each narration MP3 and writes src/narration/audio-durations.ts.
 *
 * Architecture committee Q1/Q4: paragraph length is a *result* of the
 * narration, measured post-TTS — not a hardcoded guess. The video composition
 * derives every scene's length from the file this produces.
 */
import { parseFile } from "music-metadata";
import { writeFileSync, existsSync } from "fs";
import path from "path";
import { sceneFilenames, type SceneKey } from "../../src/narration/scenes";
import { VERSIONS } from "../../src/version";

const AUDIO_DIR = path.resolve(__dirname, "../../public/audio");
const OUT_FILE = path.resolve(
  __dirname,
  "../../src/narration/audio-durations.ts",
);

export async function writeAudioDurations(): Promise<void> {
  const entries: [SceneKey, number][] = [];

  for (const scene of Object.keys(sceneFilenames) as SceneKey[]) {
    const file = path.join(AUDIO_DIR, `${sceneFilenames[scene]}.mp3`);
    if (!existsSync(file)) {
      throw new Error(
        `Missing narration audio: ${file}\n` +
          `Run "npm run generate-audio" before measuring.`,
      );
    }
    const { format } = await parseFile(file);
    if (!format.duration || format.duration <= 0) {
      throw new Error(`Could not read a valid duration from ${file}`);
    }
    entries.push([scene, Number(format.duration.toFixed(2))]);
  }

  const body = entries.map(([k, d]) => `  ${k}: ${d},`).join("\n");
  const contents =
    "// Generated by scripts/measure-audio.ts — do not edit by hand.\n" +
    "// Narration audio durations in seconds, measured post-TTS.\n" +
    "// The video composition derives each scene's length from these values.\n" +
    `// TTS voice: ${VERSIONS.ttsVoice}\n` +
    'import type { NarrationSet } from "./texts";\n\n' +
    "export const audioDurations: Record<keyof NarrationSet, number> = {\n" +
    `${body}\n` +
    "};\n";

  writeFileSync(OUT_FILE, contents, "utf8");
  console.log(`  wrote ${path.relative(process.cwd(), OUT_FILE)}`);
  for (const [k, d] of entries) console.log(`    ${k}: ${d}s`);
}
